package eci.aygo.eciuber.model.enums;

public enum VehicleType {

	SEDAN, SUV, COUPE, CONVERTIBLE, HATCHBACK, WAGON, PICKUP_TRUCK, MINIVAN, VAN, SPORTS_CAR, ELECTRIC_VEHICLE,
	HYBRID_CAR, LUXURY_CAR, CROSSOVER, ROADSTER, OFF_ROAD_VEHICLE, MUSCLE_CAR, LIMOUSINE
}
